Apply changes from P3187R1
cplusplus/sender-receiver pull request #254
Opened 2024-06-27 16:31 UTC by lewissbaker

Removes the following facilities as specified in P3187R1:
* `ensure_started()`
* `execute()`
* `start_detached()`

Also removes the following facility as it does not make sense any more:
* `execute_may_block_caller`

Note: `ensure_started()` algorithm had wording shared with `split()`
The common wording has now been simplified to now only describe `split()`.

2024-06-27 16:46 UTC, inbal2l approved these changes

2024-06-27 18:02 UTC, ericniebler requested changes
for thoroughness we should also remove mentions of `start_detached`, `execute`, and `ensure_started` from other parts of the paper.

2024-06-27 18:10 UTC, ericniebler commented on execution.bs
> -    <code><i>shared-cpo</i>.transform_sender(sndr)</code> is equivalent to:
this and the below is wrong. we need a _`split-impl-tag`_, and the _`impls-for`_ below needs to be specialized for it.

2024-06-27 18:30 UTC, ericniebler commented on execution.bs
> +            sh_state->result.template emplace&lt;err_tuple_t>(set_error, current_exception());
```suggestion
            using tuple_t = tuple&lt;set_error_t, exception_ptr>;
            sh_state->result.template emplace&lt;tuple_t>(set_error, current_exception());
```

2024-06-27 18:39 UTC, lewissbaker commented
> for thoroughness we should also remove mentions of `start_detached`, `execute`, and `ensure_started` from other parts of the paper.

I wasn't sure whether to leave them there but just add notes that they are no longer in the design or just remove them wholesale.

2024-06-27 18:41 UTC, lewissbaker commented on execution.bs
> +                  - If `c` is `false`, inserts `&state` into `state.sh_state->waiting_states`.
The code immediately below the 'atomic' block which handles the `c` is `true` case.

2024-06-27 21:34 UTC, ericniebler commented on execution.bs
> +                  - If `c` is `false`, inserts `&state` into `state.sh_state->waiting_states`.
It amounts to the same thing, no?

2024-06-28 00:38 UTC, ericniebler commented on execution.bs
> +                  - If `c` is `false`, inserts `&state` into `state.sh_state->waiting_states`.
no, it's not! i see the point of your change now. thanks for spotting this bug.

2024-06-28 00:46 UTC, ericniebler approved these changes

2024-06-28 00:48 UTC, merged